FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install -r Requirements.txt && \
    pip install dagster dagster-celery celery redis

ENV DAGSTER_HOME=/app

CMD ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]