FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN mkdir -p /opt/dagster/dagster_home

RUN pip install --upgrade pip && \
    pip install -r Requirements.txt && \
    pip install dagster dagster-celery celery redis

ENV DAGSTER_HOME=/opt/dagster/dagster_home

CMD ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
